
phases: 
  install: 
    commands: 
      # install Node LTS
      - echo Installing Node LTS...
      - curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
      - apt install -y nodejs
  prebuild:
    commands:
      # install dependencies
      - echo Installing dependencies...
      - npm install 
  build:
    commands:
      # build app
      - echo Building App...
      - npm run build

artifacts:
  files: 
    - "**/*"
  discard-paths: no
  base-directory: dist

